// <auto-generated />
namespace Scheduler.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class DisciplinesYet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DisciplinesYet));
        
        string IMigrationMetadata.Id
        {
            get { return "201911121713517_DisciplinesYet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
